name: Apple Binaries

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  linking:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Tolgee CLI
        run: npm install --global @tolgee/cli

      - name: Install Cocoapods
        run: brew install cocoapods

      - name: Build
        run: ./gradlew core:build

      - name: Framework Tolgee
        continue-on-error: true
        run: ./gradlew core:assembleTolgeeXCFramework || ./gradlew core:assembleXCFramework

      - name: Framework Tolgee Release
        continue-on-error: true
        run: ./gradlew core:assembleTolgeeReleaseXCFramework || ./gradlew core:assembleReleaseXCFramework

      - name: Framework Tolgee Debug
        continue-on-error: true
        run: ./gradlew core:assembleTolgeeDebugXCFramework || ./gradlew core:assembleDebugXCFramework

      - name: Create XCFramework Archive
        run: |
          tar -czf Tolgee-release.xcframework.tar.gz -C core/build/XCFrameworks/release/Tolgee.xcframework
          tar -czf Tolgee-debug.xcframework.tar.gz -C core/build/XCFrameworks/debug/Tolgee.xcframework

      - name: Upload XCFramework to Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Tolgee-release.xcframework.tar.gz
            Tolgee-debug.xcframework.tar.gz

      - name: Upload XCFramework to action packages
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            Tolgee-release.xcframework.tar.gz
            Tolgee-debug.xcframework.tar.gz